services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/sleepr
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/sleepr    

  mongo:
    image: mongo
    ports:
      - '27018:27017'  # Expose to host for Compass
    volumes:
      - mongo_data:/data/db  # Persist Mongo data

volumes:
  mongo_data:
